version: '3'
services:
  mysql:
    container_name: mysql-java-gui
    image: mysql
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_ALLOW_EMPTY_PASSWORD: true 
      MYSQL_DATABASE: gui
      # MYSQL_USER: 
      # MYSQL_PASSWORD: 